### ISSUE TITLE
Add blank issue templates to repo

### ISSUE THREAD

**Issue by chelseyklein** [hackforla/devops-security#16]
### Overview
We want to make it as easy as possible to create issues. Refer to the website team's repo as a reference

### Action Items
Create the following issue templates inside of the .github/ISSUE_TEMPLATE directory:
- [x] Follow the [contribution guide](https://github.com/hackforla/devops-security/blob/main/CONTRIBUTING.md) to fork and clone the code repository
- [x] Create and checkout a new branch `git checkout -b 16-add-issue-templates`
- [x] add blank issue form with no dependency [example](https://github.com/hackforla/website/issues/new?assignees=&labels=role+missing%2CComplexity%3A+Missing%2CFeature+Missing%2Csize%3A+missing%2CDraft&projects=&template=blank-issue-form-with-no-dependency.yml)
- [x] add blank issue form with dependency [example](https://github.com/hackforla/website/issues/new?assignees=&labels=role+missing%2CComplexity%3A+Missing%2CFeature+Missing%2Csize%3A+missing%2CDraft&projects=&template=blank-issue-form-with-dependency.yml)
- [x] add blank issue template [example](https://github.com/hackforla/website/issues/new?assignees=&labels=Complexity%3A+Missing%2C+Feature+Missing%2C+role+missing%2C+size%3A+missing&projects=&template=blank-issue-template.md&title=)
- [x] stage changes for commit `git add /path/to/file` - run `git status` to easily copy
- [x] commit changes `git commit -m "changes you made"`
- [x] push changes `git push --set-upstream origin your-branch-name`

### Resources
Issue templates for the website team can be referenced [here](https://github.com/hackforla/website/tree/gh-pages/.github/ISSUE_TEMPLATE)

**Comment by awlFCCamp** [comment]
Availability: 3/16 3/17
ETA: EOD 3/18
