### ISSUE TITLE
Restructure backend.tf to accomodate local development

### ISSUE THREAD

**Issue by chelseyklein** [hackforla/devops-security#17]
### Overview
There are obstacles to testing local development in personal AWS accounts. One is that the backend state for each account cannot use the same bucket name - requiring users to change the code manually before pushing changes to the repo. 

In order to better facilitate local development for users using a personal AWS account, we need to provide a shell for the backend.tf code (instead of hardcoding it) and update the GitHub Action workflows to use a `prod.backend.tfvars` file. 

### Action Items
- [x] Update the backend.tf file and replace w/ the following (we need it empty)
```
terraform {
  backend "s3" {
  }
}
```
- [x] Create a `prod.backend.tfvars` file with the following configuration:
```
bucket         = "hfla-ops-terraform-state"
key            = "devops-security/terraform.tfstate"
region         = "us-west-2"
dynamodb_table = "hfla_ops_terraform_table"
encrypt        = true
```
- [x] Add instructions to `CONTRIBUTING.md` for developers to create a backend.tfvars file w/ their backend configs
```
bucket         = "dev-specific-hfla-ops-terraform-state"
key            = "devops-security/terraform.tfstate"
region         = "us-west-2"
dynamodb_table = "dev-specific-hfla_ops_terraform_table"
encrypt        = true
```
- [x] update the Terraform workflows ([Terraform Plan Workflow](https://github.com/hackforla/devops-security/blob/main/.github/workflows/terraform-plan.yaml) / [Terraform Apply Workflow](https://github.com/hackforla/devops-security/blob/main/.github/workflows/terraform-apply.yaml)) to add the below to the dflook blocks
```
with:
  backend_config_file: prod.backend.tfvars
```
- [x] add `backend.tfvars` to .gitignore
- [x] push code changes and open a PR to test

### Resources
- https://github.com/dflook/terraform-plan#inputs

**Comment by ale210** [comment]
all set

**Comment by here** [comment]
Linking to PR at https://github.com/hackforla/devops-security/pull/44
