### ISSUE TITLE
Write GitHub Actions for running Terraform stages

### ISSUE THREAD

**Issue by chelseyklein** [hackforla/devops-security#30]
### Dependencies
- [x] hackforla/ops#115 
- [x] hackforla/ops#106 

### Overview
In order to manage IAM resources as code using Terraform, we will need the ability to run a plan on PR creation and an apply when the PR is merged into main. 

[@dflook](https://github.com/dflook) created some pretty great GitHub Actions that work well with this workflow. We could follow [this established pattern](https://github.com/dflook/terraform-github-actions#terraform-plan-pr-approval) 

### Action Items
- [x] Create a GitHub Action (GHA) `terraform-plan.yaml` for the Terraform plan workflow
  - [x] action is triggered on PR creation | [example using dflook's GitHub action](https://github.com/dflook/terraform-github-actions#terraform-plan-pr-approval)
    - [x] only when files end in .tf
      - we will have readme and other files in these directories, and we don't want changes there to trigger this workflow
  - [x] results of the plan are written back to the PR as a comment 

- [x] Create a GHA `terraform-apply.yaml` for the Terraform apply workflow
  - [x] action is triggered on PR merge to main
    - [x] only when files end in .tf  

### Resources/Instructions
[DevOps Security code repository](https://github.com/hackforla/devops-security) | PM a [CoP lead](https://github.com/hackforla/ops/wiki/Community#ops-community-of-practice-cop-leads) in Slack if you don't already have access.

[dflook GitHub Actions](https://github.com/dflook/terraform-github-actions#terraform-and-opentofu-github-actions-)

@Tyson-miller wrote a [GitHub Action](https://github.com/hackforla/incubator/pull/30/files) for running Terraform plan on incubator projects...though our needs are simpler

**Comment by chelseybeck** [comment]
Closed w/ these prs
- https://github.com/hackforla/devops-security/pull/32
- https://github.com/hackforla/devops-security/pull/31
