### ISSUE TITLE
Create IAM read-only accounts for DevOps users

### ISSUE THREAD

**Issue by chelseyklein** [hackforla/devops-security#8]
Member name: Jim Juarez
GitHub handle: JimmyJuarez10
Project: Civic Tech Jobs
Access Level: read-only

**Comment by brittanyms** [comment]
Member name: Brittany Sims
GitHub handle: brittanyms
Project: Dev-ops security
Access Level: read-only

**Comment by freaky4wrld** [comment]
Member name: Nayan Bhatt
Project: Devonshire security 
Access: Read only

**Comment by Shikha0428** [comment]
Member name: Shikha Yadav
GitHub handle: Shikha0428
Project: Dev-ops security
Access Level: read-only

**Comment by shinjonathan** [comment]
Member name: Jonathan Shin
Github handle: Shikha0428
Project: Dev-ops security
Access Level: read-only

**Comment by samuelusc** [comment]
Member name: Samuel Wang
Github handle: samuelusc
Project: Dev-ops security
Access Level: read-only

**Comment by abbyz123** [comment]
Member name: Zoey Zhang
Github handle: abbyz123
Project: Dev-ops security
Access Level: read-only

**Comment by awlFCCamp** [comment]
Member name: Angela Lee
Github handle: awlfccamp
Project:website
Access Level: read-only
